### ISSUE TITLE
Keep getting the same error logs

### ISSUE THREAD

**Issue by Dumeng** [gioboa/jira-plugin#16]
```bash
[2018-09-21 11:18:25.947] [renderer2] [error] Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
	at IssueLinkProvider.get projectNames [as projectNames] (/Users/user/.vscode/extensions/gioboa.jira-plugin-0.8.0/out/src/shared/document-link-provider.js:10:63)
	at document.getText.split.reduce (/Users/user/.vscode/extensions/gioboa.jira-plugin-0.8.0/out/src/shared/document-link-provider.js:17:90)
	at Array.reduce (<anonymous>)
	at IssueLinkProvider.provideDocumentLinks (/Users/user/.vscode/extensions/gioboa.jira-plugin-0.8.0/out/src/shared/document-link-provider.js:17:14)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:758:465
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideLinks (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:758:419)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:768:893
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:761:91)
	at e.$provideDocumentLinks (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:768:855)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by gioboa** [comment]
Hi @Dumeng, which are the steps to reproduce it?

**Comment by gioboa** [comment]
Found the problem.
Solved with this [commit](https://github.com/gioboa/jira-plugin/commit/c47cf6bef8233505174142ad727d247b0edc4ed1)

**Comment by Dumeng** [comment]
Tx a lot. And I get the error message 'Wrong parameter. No issues found for AELJ project.' with a specific project. How can I get the error log, so I can raise an issue?

**Comment by gioboa** [comment]
This message appear when the Jira search fail.

So try this steps:
1 - restart VS Code
2 - select project (I think you have already select AELJ)
3 - from explorer you have all project issues
4 - from three dot button (...) try to change the filter

The error message 'Wrong parameter. No issues found for AELJ project.' persist?

**Comment by gioboa** [comment]
@Dumeng Any news?

**Comment by Dumeng** [comment]
This only happens when I choose 'All issues'

**Comment by gioboa** [comment]
When you choose 'all issues' under the hood the plugin do this search in Jira:
`project = project_name ORDER BY updated DESC`
Really simple.
If you copy and paste this search in your Jira web application it works?

**Comment by Dumeng** [comment]
Yes, it works on JIRA website

**Comment by gioboa** [comment]
mmm, really strange. 😕 
I will improve the error messages so we can understand the real problem. 👍

**Comment by gioboa** [comment]
In v. 0.8.3 I improved error messages. Please try now and let me know.

**Comment by Dumeng** [comment]
The issue fixed in the new version. I don't get the error anymore.
